-- Create custom enum type for flashcard sources
-- This enum tracks the origin of each flashcard:
-- - ai-full: Generated by AI and used without edits
-- - ai-edited: Generated by AI but edited by user
-- - manual: Created manually by user
create type flashcard_source as enum ('ai-full', 'ai-edited', 'manual'); 